Dashboard and Income pages
RafoelAz/FamilyBudget pull request #8
Opened 2021-01-28 18:32 UTC by alpopkov

Created Dashboard and Income pages

2021-01-29 10:48 UTC, M1chman approved these changes

2021-01-29 13:55 UTC, EugenAz commented on ui/src/components/header.css
> +.container__logoImg {
как правило хорошего тона в css не используют camelcase. Слова разделяются тире "-", БЕМ добавил так же двойное тире -- и двойное подчеркивание __

2021-01-29 13:56 UTC, EugenAz commented on ui/src/components/header.css
> +  margin: 0px 0px 0px 0px;
эту строку можно упростить:
`margin: 0;`

2021-01-29 13:56 UTC, EugenAz commented on ui/src/components/header.jsx
> +          <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#/">
className вместо class

2021-01-29 13:56 UTC, EugenAz commented on ui/src/components/header.jsx
> +            <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#/">
и тут

2021-01-29 13:57 UTC, EugenAz commented on ui/src/components/header.jsx
> +              <a class="nav-link" href="#/">
и везде))

2021-01-29 13:57 UTC, EugenAz commented on ui/src/components/main.jsx
> +  return <div className="main" />;
`<main>` тег для большей семантичности.

2021-01-29 13:58 UTC, EugenAz commented on ui/src/pages/dashboard.page.jsx
> +    <body>
тег `<body>` здесь лишний

2021-01-29 14:00 UTC, EugenAz requested changes
Я оставил там всяких комментариев :)

2021-01-30 12:35 UTC, EugenAz commented on ui/src/pages/income.page.css
> +.row {
помнишь я описывал проблему с классом .btn? вот тут то же самое.
В общем, когда ты вот так "переопределяешь" глобальные классы в бутстрапе - ты должен понимать, что каждый раз, когда кто-то будет использовать эти классы - они получат вот этот твой стиль. И скорее всего, это будет для людей непонятным сюрпризом - А почему я использую обычный bootstrap класс, а получаю странный результат)) И это займет некоторое время понять, что все дело в том, что вот тут лежит вот этот стиль) Понимаешь?

2021-01-30 19:32 UTC, merged